export const samplePatientList = [
  {
    seq: '1',
    id: '',
    socketId: '',
    name: '환자 1번',
    age: '32',
    memberType: '재외국민',
    gender: '남',
    phone: '010-1111-2222',
    disease: '열',
    treatCnt: '15',
    treatState: '대기',
    receiptTime: '09:00',
    waitTime: '45분',
    status: 'WAIT',
  },
  {
    seq: '2',
    id: '13247',
    socketId: '42345',
    name: '김길동',
    age: '41',
    memberType: '내국인',
    gender: '남',
    phone: '010-1111-2222',
    disease: '기침',
    treatCnt: '5',
    treatState: '대기',
    receiptTime: '09:25',
    waitTime: '25분',
    status: 'WAIT',
  },
  {
    seq: '3',
    id: '13247',
    socketId: '42345',
    name: '이순이',
    age: '26',
    memberType: '내국인',
    gender: '여',
    phone: '010-1111-2222',
    disease: '복통',
    treatCnt: '3',
    treatState: '대기',
    receiptTime: '10:00',
    waitTime: '35분',
    status: 'WAIT',
  },
];
