import { LNG_KEY } from '@src/i18n';

export const memberText = {
  memberInfoMainTitle: LNG_KEY.USER_INFO_TITLE,
  memberPwTitleHeader: LNG_KEY.HEADER_USER_PW_TITLE,
  memberAddressSearchHeader: LNG_KEY.HEADER_ADDRESS_SEARCH_TITLE,
  memberType: LNG_KEY.USER_TYPE,
  memberTypeChange: LNG_KEY.USER_TYPE_CHANGE,
  memberTypeNative: LNG_KEY.USER_TYPE_NATIVE,
  memberTypeOverseas: LNG_KEY.USER_TYPE_OVERSEAS,
  memberResiderceInternal: LNG_KEY.USER_RESIDENCE_INTERNAL,
  memberResiderceOverseas: LNG_KEY.USER_RESIDENCE_OVERSEAS,
  memberName: LNG_KEY.USER_NAME,
  memberPhone: LNG_KEY.USER_PHONE,
  memberPhoneChange: LNG_KEY.USER_PHONE_CHANGE,
  passwordChange: LNG_KEY.PW_CHANGE,
  labelEmail: LNG_KEY.EMAIL,
  labelPw: LNG_KEY.LABEL_PW,
  placehoderMemberName: LNG_KEY.PLACEHOLDER_USER_NAME,
  placehoderMemberPhone: LNG_KEY.PLACEHOLDER_USER_PHONE,
  placehoderEmail: LNG_KEY.PLACEHOLDER_EMAIL,
  placehoderPassword: LNG_KEY.PLACEHOLDER_PW,
  placehoderPasswordCheck: LNG_KEY.PLACEHOLDER_PW_CHECK,
  placehoderPwRegister: LNG_KEY.PLACEHOLDER_PW_REG,
  placehoderAddressSearch: LNG_KEY.PLACEHOLDER_ADDRESS_SEARCH,
  duplicateCheck: LNG_KEY.DUPLICATE_CHECK,
  check: LNG_KEY.CHECK,
  memberAddress: LNG_KEY.USER_ADDRESS,
  memberLinkedSns: LNG_KEY.USER_LINKED_SNS,
  btnSave: LNG_KEY.BTN_SAVE,
};
